WEB_1 : How to Work With CSV Files in Python?

https://www.analyticsvidhya.com/blog/2021/08/python-tutorial-working-with-csv-file-for-data-science/

In [1]:
import csv

# Open the CSV file in read mode
with open('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', 'r') as csvfile:
  # Create a reader object
  csv_reader = csv.reader(csvfile)
  
  # Iterate through the rows in the CSV file
  for row in csv_reader:
    # Access each element in the row
    print(row)

<>:4: SyntaxWarning: invalid escape sequence '\T'
<>:4: SyntaxWarning: invalid escape sequence '\T'
C:\Users\FILIPUS FERRY\AppData\Local\Temp\ipykernel_14860\2270953849.py:4: SyntaxWarning: invalid escape sequence '\T'
  with open('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', 'r') as csvfile:

['Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats']
['1;Tesla;Model 3;57.5;104;6.1 sec;201 km/h;415 km;139 Wh/km;690 km/h;â‚¬41', '970;â‚¬41', '990;Â£39', '990;Rear Wheel Drive;Towbar possible;1000;5']
['2;Tesla;Model Y;57.5;137;6.9 sec;217 km/h;350 km;164 Wh/km;580 km/h;â‚¬45', '970;â‚¬45', '990;Â£44', '990;Rear Wheel Drive;Towbar possible;1600;5']
['3;Tesla;Model Y Long Range Dual Motor;75;130;5.0 sec;217 km/h;435 km;172 Wh/km;670 km/h;â‚¬55', '970;â‚¬52', '990;Â£52', '990;All Wheel Drive;Towbar possible;1600;5']
['4;Tesla;Model 3 Long Range Dual Motor;75;106;4.4 sec;201 km/h;500 km;150 Wh/km;770 km/h;â‚¬50', '970;â‚¬49', '990;Â£49', '990;All Wheel Drive;Towbar possible;1000;5']
['5;Tesla;Model Y Long Range RWD;75;109;5.9 sec;217 km/h;460 km;163 Wh/km;710 km/h;â‚¬49', '970;â‚¬49', '990;N/A;Rear Wheel Drive;Towbar possible;1600;5']
['6;Byd;ATTO 3;60.5;121;7.3 sec;160 km/h;330 km;183 Wh/km;370 km/h;â‚¬37', '990;â‚¬38', '990;Â£37', '195;Front Wheel Drive;;;5']
['7;Mg;MG4 Electric 64 kWh;61.7;102;7.9 sec;160 km/h;360 km;171 Wh/km;630 km/h;â‚¬39', '990;â‚¬35', '785;Â£29', '495;Rear Wheel Drive;Towbar possible;500;5']
['8;Byd;SEAL 82.5 kWh AWD Excellence;82.5;107;3.8 sec;180 km/h;490 km;168 Wh/km;540 km/h;â‚¬50', '990;â‚¬50', '990;Â£48', '695;All Wheel Drive;;;5']
['9;Tesla;Model Y Performance;75;152;3.8 sec;250 km/h;415 km;181 Wh/km;640 km/h;â‚¬60', '790;â‚¬58', '990;Â£59', '990;All Wheel Drive;Towbar possible;1600;5']
['10;Bmw;i4 eDrive40;80.7;122;5.7 sec;190 km/h;515 km;157 Wh/km;800 km/h;â‚¬59', '200;â‚¬62', '992;Â£57', '890;Rear Wheel Drive;Towbar possible;1600;5']
['11;Citroen;e-C3;44;90;11.0 sec;135 km/h;265 km;166 Wh/km;340 km/h;â‚¬23', '300;â‚¬24', '290;* Â£21', '000;Front Wheel Drive;Towbar possible;550;5']
['12;Bmw;iX xDrive40;71;225;6.1 sec;200 km/h;360 km;197 Wh/km;480 km/h;â‚¬77', '300;â‚¬84', '998;Â£69', '905;All Wheel Drive;Towbar possible;2500;5']
['13;Volkswagen;ID.4 Pro;77;114;6.7 sec;180 km/h;435 km;177 Wh/km;650 km/h;â‚¬46', '335;â‚¬49', '990;Â£46', '035;Rear Wheel Drive;Towbar possible;1000;5']
['14;Byd;DOLPHIN 60.4 kWh;60.5;101;7.0 sec;160 km/h;340 km;178 Wh/km;340 km/h;â‚¬32', '990;â‚¬35', '490;Â£30', '195;Front Wheel Drive;Towbar possible;0;5']
['15;Volvo;EX30 Single Motor ER;64;118;5.3 sec;180 km/h;360 km;178 Wh/km;600 km/h;â‚¬41', '790;â‚¬41', '495;Â£38', '545;Rear Wheel Drive;Towbar possible;1400;5']
['16;Tesla;Model S Plaid;95;199;2.3 sec;282 km/h;560 km;170 Wh/km;780 km/h;â‚¬110', '970;â‚¬108', '990;* Â£100', '000;All Wheel Drive;Towbar possible;1600;5']
['17;Tesla;Model S Dual Motor;95;167;3.2 sec;250 km/h;575 km;165 Wh/km;800 km/h;â‚¬95', '970;â‚¬93', '990;* Â£85', '000;All Wheel Drive;Towbar possible;1600;5']
['18;Kia;Niro EV;64.8;111;7.8 sec;167 km/h;385 km;168 Wh/km;390 km/h;â‚¬45', '690;â‚¬39', '995;Â£37', '295;Front Wheel Drive;Towbar possible;750;5']
['19;Hyundai;Kona Electric 65 kWh;65.4;116;7.8 sec;170 km/h;390 km;168 Wh/km;400 km/h;â‚¬47', '190;â‚¬43', '995;Â£38', '595;Front Wheel Drive;Towbar possible;750;5']
['20;Tesla;Model 3 Performance;75;135;3.2 sec;262 km/h;455 km;165 Wh/km;700 km/h;â‚¬57', '970;â‚¬56', '990;Â£59', '990;All Wheel Drive;;;5']
['21;Byd;HAN;85.4;146;3.9 sec;180 km/h;475 km;180 Wh/km;450 km/h;â‚¬69', '020;â‚¬69', '990;N/A;All Wheel Drive;;;5']
['22;Cupra;Born 150 kW - 58 kWh;58;113;7.3 sec;160 km/h;350 km;166 Wh/km;470 km/h;â‚¬39', '370;â‚¬36', '939;Â£36', '475;Rear Wheel Drive;;;5']
['23;Fiat;500e Hatchback 42 kWh;37.3;149;9.0 sec;150 km/h;235 km;159 Wh/km;390 km/h;â‚¬34', '990;â‚¬34', '490;Â£31', '195;Front Wheel Drive;;;4']
['24;Byd;SEAL 82.5 kWh RWD Design;82.5;96;5.9 sec;180 km/h;500 km;165 Wh/km;550 km/h;â‚¬44', '990;â‚¬45', '990;Â£45', '695;Rear Wheel Drive;;;5']
['25;Byd;TANG;86.4;199;4.6 sec;180 km/h;355 km;243 Wh/km;420 km/h;â‚¬71', '400;â‚¬69', '990;N/A;All Wheel Drive;Towbar possible;1500;7']
['26;Dacia;Spring Electric 45;25;137;19.1 sec;125 km/h;165 km;152 Wh/km;180 km/h;â‚¬22', '550;N/A;N/A;Front Wheel Drive;;;4']
['27;Renault;Scenic E-Tech EV87 220hp;87;98;7.9 sec;170 km/h;490 km;178 Wh/km;510 km/h;â‚¬48', '900;â‚¬47', '970;Â£40', '995;Front Wheel Drive;Towbar possible;1100;5']
['28;Bmw;iX3;74;184;6.8 sec;180 km/h;385 km;192 Wh/km;520 km/h;â‚¬67', '300;â‚¬71', '462;Â£64', '165;Rear Wheel Drive;Towbar possible;750;5']
['29;Bmw;iX1 xDrive30;64.7;147;5.6 sec;180 km/h;380 km;170 Wh/km;510 km/h;â‚¬55', '000;â‚¬57', '850;Â£47', '465;All Wheel Drive;Towbar possible;1200;5']
['30;Tesla;Model Y;57.5;137;6.9 sec;217 km/h;350 km;164 Wh/km;810 km/h;â‚¬45', '970;â‚¬45', '990;Â£44', '990;Rear Wheel Drive;Towbar possible;1600;5']
['31;Skoda;Enyaq 85;77;111;6.7 sec;180 km/h;450 km;171 Wh/km;670 km/h;â‚¬48', '900;â‚¬49', '990;Â£44', '540;Rear Wheel Drive;Towbar possible;1000;5']
['32;Nio;ET7 75 kWh;70.5;208;3.8 sec;200 km/h;400 km;176 Wh/km;600 km/h;â‚¬81', '900;â‚¬84', '900;N/A;All Wheel Drive;Towbar possible;2000;5']
['33;Audi;Q6 e-tron quattro;94.9;170;5.9 sec;210 km/h;460 km;206 Wh/km;920 km/h;â‚¬74', '700;* â‚¬80', '000;Â£68', '975;All Wheel Drive;Towbar possible;2400;5']
['34;Byd;SEAL U 71.8 kWh Comfort;71.8;126;9.3 sec;175 km/h;340 km;211 Wh/km;320 km/h;N/A;â‚¬42', '990;N/A;Front Wheel Drive;;;5']
['35;Mg;ZS EV Long Range;68.3;105;8.4 sec;175 km/h;370 km;185 Wh/km;420 km/h;â‚¬37', '990;â‚¬40', '185;Â£32', '995;Front Wheel Drive;Towbar possible;500;5']
['36;Toyota;bZ4X FWD;64;144;7.5 sec;160 km/h;340 km;188 Wh/km;510 km/h;â‚¬47', '490;â‚¬45', '995;Â£46', '110;Front Wheel Drive;Towbar possible;750;5']
['37;Renault;5 E-Tech 52kWh 150hp;52;97;7.5 sec;150 km/h;330 km;158 Wh/km;420 km/h;* â‚¬32', '000;* â‚¬32', '000;* Â£28', '000;Front Wheel Drive;Towbar possible;500;5']
['38;Bmw;i4 M50;80.7;170;3.9 sec;225 km/h;450 km;179 Wh/km;700 km/h;â‚¬70', '800;â‚¬76', '786;Â£71', '085;All Wheel Drive;Towbar possible;1600;5']
['39;Renault;Megane E-Tech EV60 220hp;60;113;7.4 sec;160 km/h;380 km;158 Wh/km;530 km/h;â‚¬46', '600;â‚¬39', '370;Â£36', '995;Front Wheel Drive;Towbar possible;900;5']
['40;Rolls-royce;Spectre;102;828;4.5 sec;250 km/h;465 km;219 Wh/km;540 km/h;â‚¬379', '015;â‚¬396', '275;Â£330', '000;All Wheel Drive;;;4']
['41;Kia;EV6 Long Range 2WD;74;126;7.3 sec;185 km/h;410 km;180 Wh/km;1070 km/h;â‚¬51', '990;â‚¬50', '995;Â£45', '245;Rear Wheel Drive;Towbar possible;1600;5']
['42;Honda;e:Ny1;61.9;147;7.6 sec;160 km/h;335 km;185 Wh/km;300 km/h;â‚¬47', '590;â‚¬48', '750;Â£44', '995;Front Wheel Drive;;;5']
['43;Volkswagen;ID.3 Pro;58;122;7.3 sec;160 km/h;350 km;166 Wh/km;450 km/h;â‚¬39', '995;â‚¬44', '990;Â£37', '115;Rear Wheel Drive;Towbar possible;0;5']
['44;Renault;Zoe ZE50 R110;52;114;11.4 sec;135 km/h;315 km;165 Wh/km;230 km/h;â‚¬36', '840;â‚¬34', '895;N/A;Front Wheel Drive;;;5']
['45;Nissan;Leaf;39;144;7.9 sec;144 km/h;235 km;166 Wh/km;230 km/h;â‚¬33', '400;â‚¬35', '090;Â£28', '995;Front Wheel Drive;;;5']
['46;Lucid;Air Grand Touring;112;196;3.0 sec;270 km/h;665 km;168 Wh/km;840 km/h;â‚¬129', '000;â‚¬132', '000;N/A;All Wheel Drive;;;5']
['47;Hongqi;E-HS9 99 kWh;90;216;4.9 sec;200 km/h;370 km;243 Wh/km;430 km/h;N/A;â‚¬79', '995;N/A;All Wheel Drive;Towbar possible;1500;5']
['48;Cupra;Born 170 kW - 77 kWh;77;105;7.0 sec;160 km/h;450 km;171 Wh/km;630 km/h;â‚¬46', '450;â‚¬46', '989;Â£41', '975;Rear Wheel Drive;;;4']
['49;Zeekr;001 Long Range RWD;94;116;7.2 sec;200 km/h;525 km;179 Wh/km;710 km/h;â‚¬60', '970;â‚¬60', '490;N/A;Rear Wheel Drive;Towbar possible;1500;5']
['50;Hyundai;IONIQ 6 Long Range 2WD;74;107;7.4 sec;185 km/h;495 km;149 Wh/km;1290 km/h;â‚¬54', '000;â‚¬50', '895;Â£47', '040;Rear Wheel Drive;Towbar possible;1500;5']
['51;Hyundai;IONIQ 5 Long Range 2WD;74;132;7.3 sec;185 km/h;390 km;190 Wh/km;1020 km/h;â‚¬47', '900;â‚¬52', '895;Â£46', '945;Rear Wheel Drive;Towbar possible;1600;5']
['52;Porsche;Macan 4 Electric;95;174;5.2 sec;220 km/h;485 km;196 Wh/km;970 km/h;â‚¬84', '100;â‚¬88', '899;Â£69', '800;All Wheel Drive;Towbar possible;2000;5']
['53;Bmw;i7 xDrive60;101.7;272;4.7 sec;240 km/h;510 km;199 Wh/km;760 km/h;â‚¬139', '900;â‚¬145', '453;Â£113', '970;All Wheel Drive;Towbar possible;2000;5']
['54;Bmw;i4 eDrive35;67;134;6.0 sec;190 km/h;430 km;156 Wh/km;580 km/h;â‚¬56', '500;â‚¬59', '362;Â£49', '995;Rear Wheel Drive;Towbar possible;1600;5']
['55;Hyundai;IONIQ 5 N;80;194;3.4 sec;260 km/h;385 km;208 Wh/km;950 km/h;â‚¬74', '900;â‚¬73', '995;Â£65', '000;All Wheel Drive;;;5']
['56;Volkswagen;ID.7 Pro;77;126;6.5 sec;180 km/h;475 km;162 Wh/km;730 km/h;â‚¬56', '995;â‚¬57', '990;Â£55', '570;Rear Wheel Drive;Towbar possible;1000;5']
['57;Mercedes-benz;EQB 250+;70.5;136;8.9 sec;160 km/h;415 km;170 Wh/km;490 km/h;â‚¬53', '514;â‚¬54', '966;Â£52', '800;Front Wheel Drive;Towbar possible;1400;7']
['58;Mg;MG4 Electric 51 kWh;50.8;109;7.7 sec;160 km/h;300 km;169 Wh/km;380 km/h;â‚¬34', '990;â‚¬32', '285;Â£26', '995;Rear Wheel Drive;Towbar possible;500;5']
['59;Audi;Q4 e-tron 45;77;132;6.7 sec;180 km/h;420 km;183 Wh/km;630 km/h;â‚¬52', '950;â‚¬54', '865;Â£50', '745;Rear Wheel Drive;Towbar possible;1000;5']
['60;Kia;EV9 99.8 kWh AWD;96;170;6.0 sec;200 km/h;435 km;221 Wh/km;830 km/h;â‚¬76', '490;â‚¬71', '495;N/A;All Wheel Drive;Towbar possible;2500;7']
['61;Smart;#1 Pro+;62;126;6.7 sec;180 km/h;335 km;185 Wh/km;520 km/h;â‚¬42', '490;â‚¬42', '935;Â£35', '950;Rear Wheel Drive;Towbar possible;1600;5']
['62;Audi;Q8 e-tron 55 quattro;106;170;5.6 sec;200 km/h;505 km;210 Wh/km;640 km/h;â‚¬85', '300;â‚¬82', '985;Â£77', '800;All Wheel Drive;Towbar possible;1800;5']
['63;Nissan;Ariya 87kWh;87;117;7.6 sec;160 km/h;450 km;193 Wh/km;540 km/h;â‚¬58', '990;â‚¬47', '990;Â£44', '645;Front Wheel Drive;Towbar possible;750;5']
['64;Ford;Mustang Mach-E ER RWD;91;126;7.0 sec;180 km/h;480 km;190 Wh/km;420 km/h;â‚¬58', '500;â‚¬54', '400;Â£59', '830;Rear Wheel Drive;Towbar possible;1500;5']
['65;Bmw;iX xDrive50;105.2;213;4.6 sec;200 km/h;505 km;208 Wh/km;680 km/h;â‚¬100', '100;â‚¬105', '097;Â£102', '755;All Wheel Drive;Towbar possible;2500;5']
['66;Volvo;EX30 Single Motor;49;136;5.7 sec;180 km/h;275 km;178 Wh/km;420 km/h;â‚¬36', '590;â‚¬36', '795;Â£33', '795;Rear Wheel Drive;Towbar possible;1000;5']
['67;Bmw;iX1 eDrive20;64.7;127;8.3 sec;170 km/h;390 km;166 Wh/km;520 km/h;â‚¬47', '900;â‚¬48', '316;Â£45', '465;Front Wheel Drive;Towbar possible;750;5']
['68;Hyundai;IONIQ 6 Long Range AWD;74;135;5.1 sec;185 km/h;440 km;168 Wh/km;1150 km/h;â‚¬61', '100;â‚¬59', '395;Â£50', '540;All Wheel Drive;Towbar possible;1500;5']
['69;Kia;EV6 GT;74;198;3.5 sec;260 km/h;360 km;206 Wh/km;940 km/h;â‚¬72', '990;â‚¬69', '295;Â£62', '645;All Wheel Drive;Towbar possible;1800;5']
['70;Opel;Astra Electric;50.8;131;9.2 sec;170 km/h;320 km;159 Wh/km;510 km/h;â‚¬41', '990;â‚¬39', '999;Â£37', '795;Front Wheel Drive;Towbar possible;0;5']
['71;Mercedes-benz;EQA 250;66.5;129;8.6 sec;160 km/h;395 km;168 Wh/km;570 km/h;â‚¬50', '777;N/A;N/A;Front Wheel Drive;Towbar possible;1500;5']
['72;Peugeot;e-3008 98 kWh Long Range;98;111;8.9 sec;170 km/h;510 km;192 Wh/km;660 km/h;* â‚¬55', '000;* â‚¬55', '000;* Â£52', '000;Front Wheel Drive;Towbar possible;1200;5']
['73;Mercedes-benz;EQS 450+;108.4;175;6.1 sec;210 km/h;635 km;171 Wh/km;950 km/h;â‚¬109', '551;â‚¬112', '720;N/A;Rear Wheel Drive;Towbar possible;750;5']
['74;Polestar;2 Long Range Single Motor;79;112;6.2 sec;205 km/h;470 km;168 Wh/km;700 km/h;â‚¬49', '975;â‚¬51', '200;Â£48', '950;Rear Wheel Drive;Towbar possible;1500;5']
['75;Peugeot;e-3008 73 kWh;73;129;8.7 sec;170 km/h;385 km;190 Wh/km;440 km/h;â‚¬48', '650;â‚¬48', '190;Â£45', '850;Front Wheel Drive;Towbar possible;1250;5']
['76;Volkswagen;ID. Buzz Pro;77;192;10.2 sec;145 km/h;345 km;223 Wh/km;480 km/h;â‚¬64', '581;â‚¬66', '160;Â£58', '915;Rear Wheel Drive;Towbar possible;1000;5']
['77;Hyundai;IONIQ 5 Long Range AWD;74;154;5.1 sec;185 km/h;385 km;192 Wh/km;1010 km/h;â‚¬59', '200;â‚¬60', '995;Â£50', '445;All Wheel Drive;Towbar possible;1600;5']
['78;Jeep;Avenger Electric;50.8;127;9.0 sec;150 km/h;310 km;164 Wh/km;500 km/h;â‚¬38', '500;â‚¬39', '500;Â£34', '800;Front Wheel Drive;;;5']
['79;Hyundai;IONIQ 5 Standard Range 2WD;54;162;8.5 sec;185 km/h;295 km;183 Wh/km;720 km/h;â‚¬43', '900;â‚¬49', '295;Â£43', '445;Rear Wheel Drive;Towbar possible;750;5']
['80;Zeekr;001 Performance AWD;94;127;3.8 sec;200 km/h;500 km;188 Wh/km;670 km/h;â‚¬63', '970;â‚¬63', '490;N/A;All Wheel Drive;Towbar possible;2000;5']
['81;Bmw;i5 eDrive40 Sedan;81.2;165;6.0 sec;193 km/h;470 km;173 Wh/km;750 km/h;â‚¬70', '200;â‚¬77', '572;Â£74', '105;Rear Wheel Drive;Towbar possible;1500;5']
['82;Citroen;e-C4;46.3;127;9.7 sec;150 km/h;290 km;160 Wh/km;460 km/h;â‚¬36', '040;â‚¬37', '830;Â£31', '995;Front Wheel Drive;;;5']
['83;Ford;Explorer Extended Range RWD;77;115;6.4 sec;180 km/h;430 km;179 Wh/km;640 km/h;â‚¬49', '500;â‚¬45', '950;Â£45', '875;Rear Wheel Drive;Towbar possible;1000;5']
['84;Kia;EV6 Long Range AWD;74;146;5.2 sec;185 km/h;400 km;185 Wh/km;1050 km/h;â‚¬55', '980;â‚¬59', '995;Â£51', '745;All Wheel Drive;Towbar possible;1600;5']
['85;Mazda;MX-30;30;212;9.7 sec;140 km/h;170 km;176 Wh/km;170 km/h;â‚¬35', '990;â‚¬36', '440;Â£31', '250;Front Wheel Drive;;;5']
['86;Alfa romeo;Junior Elettrica 54 kWh Veloce;50.8;152;7.0 sec;150 km/h;305 km;167 Wh/km;490 km/h;* â‚¬46', '000;* â‚¬45', '000;* Â£42', '000;Front Wheel Drive;;;5']
['87;Volvo;EX30 Twin Motor Performance;64;145;3.6 sec;180 km/h;335 km;191 Wh/km;560 km/h;â‚¬48', '490;â‚¬49', '995;Â£40', '995;All Wheel Drive;Towbar possible;1600;5']
['88;Mini;Countryman E;64.7;117;8.6 sec;170 km/h;385 km;168 Wh/km;520 km/h;â‚¬43', '500;â‚¬43', '490;Â£42', '080;Front Wheel Drive;Towbar possible;750;5']
['89;Nio;ET5 100 kWh;90;140;4.0 sec;200 km/h;500 km;180 Wh/km;520 km/h;â‚¬68', '500;â‚¬71', '700;N/A;All Wheel Drive;Towbar possible;1400;5']
['90;Volkswagen;ID. Buzz LWB Pro S;86;199;8.0 sec;160 km/h;370 km;232 Wh/km;470 km/h;* â‚¬73', '000;* â‚¬73', '000;* Â£65', '000;Rear Wheel Drive;Towbar possible;;7']
['91;Tesla;Model X Dual Motor;95;226;3.9 sec;250 km/h;475 km;200 Wh/km;660 km/h;â‚¬100', '970;â‚¬100', '993;* Â£105', '000;All Wheel Drive;Towbar possible;2250;7']
['92;Volkswagen;ID.7 Pro S;86;120;7.0 sec;180 km/h;520 km;165 Wh/km;800 km/h;* â‚¬60', '000;* â‚¬60', '000;* Â£59', '000;Rear Wheel Drive;;;5']
['93;Mg;MG4 Electric 77 kWh;74.4;101;6.5 sec;180 km/h;425 km;175 Wh/km;430 km/h;â‚¬45', '990;â‚¬41', '285;Â£36', '495;Rear Wheel Drive;Towbar possible;500;5']
['94;Dacia;Spring Electric 45;25;109;19.1 sec;125 km/h;165 km;152 Wh/km;180 km/h;* â‚¬18', '000;â‚¬18', '950;Â£14', '995;Front Wheel Drive;;;4']
['95;Mg;MG5 Electric Long Range;57.4;112;7.7 sec;185 km/h;335 km;171 Wh/km;330 km/h;â‚¬38', '490;â‚¬38', '885;Â£30', '995;Front Wheel Drive;Towbar possible;500;5']
['96;Kia;EV9 99.8 kWh AWD GT-Line;96;193;5.3 sec;200 km/h;425 km;226 Wh/km;810 km/h;â‚¬82', '380;â‚¬78', '895;Â£73', '245;All Wheel Drive;Towbar possible;2500;7']
['97;Mercedes-benz;EQV 300 Long;90;266;12.1 sec;160 km/h;315 km;286 Wh/km;320 km/h;â‚¬79', '048;â‚¬88', '626;N/A;Front Wheel Drive;;;7']
['98;Byd;SEAL U 87 kWh Design;87;114;9.6 sec;175 km/h;405 km;215 Wh/km;370 km/h;N/A;â‚¬45', '990;N/A;Front Wheel Drive;;;5']
['99;Byd;DOLPHIN 44.9 kWh Active;44.9;115;12.3 sec;150 km/h;255 km;176 Wh/km;260 km/h;* â‚¬28', '000;â‚¬29', '990;* Â£26', '000;Front Wheel Drive;;;5']
['100;Smart;#1 Brabus;62;152;3.9 sec;180 km/h;325 km;191 Wh/km;500 km/h;â‚¬48', '990;â‚¬48', '895;Â£43', '450;All Wheel Drive;Towbar possible;1600;5']
['101;Lotus;Eletre;109;202;4.5 sec;250 km/h;495 km;220 Wh/km;1040 km/h;â‚¬96', '990;â‚¬98', '690;Â£90', '805;All Wheel Drive;Towbar possible;2250;5']
['102;Renault;Zoe ZE50 R135;52;117;9.5 sec;140 km/h;310 km;168 Wh/km;230 km/h;â‚¬37', '840;â‚¬36', '195;Â£29', '995;Front Wheel Drive;;;5']
['103;Maxus;MIFA 9;84;197;9.2 sec;180 km/h;365 km;230 Wh/km;420 km/h;â‚¬68', '990;N/A;Â£65', '290;Front Wheel Drive;Towbar possible;1000;7']
['104;Lexus;RZ 450e;64;218;5.6 sec;160 km/h;320 km;200 Wh/km;480 km/h;â‚¬68', '000;â‚¬67', '495;Â£64', '500;All Wheel Drive;Towbar possible;750;5']
['105;Mercedes-benz;EQE 350+;90.6;155;6.4 sec;210 km/h;530 km;171 Wh/km;790 km/h;N/A;â‚¬82', '028;N/A;Rear Wheel Drive;Towbar possible;750;5']
['106;Bmw;i5 M60 xDrive Sedan;81.2;254;3.8 sec;230 km/h;420 km;193 Wh/km;670 km/h;â‚¬99', '500;â‚¬108', '427;Â£97', '745;All Wheel Drive;Towbar possible;2000;5']
['107;Cupra;Tavascan VZ;77;141;5.6 sec;180 km/h;430 km;179 Wh/km;640 km/h;* â‚¬58', '000;* â‚¬60', '000;* Â£55', '000;All Wheel Drive;;;5']
['108;Xpeng;G9 RWD Standard Range;75.8;148;6.4 sec;200 km/h;395 km;192 Wh/km;830 km/h;â‚¬57', '600;â‚¬59', '188;N/A;Rear Wheel Drive;Towbar possible;1500;5']
['109;Subaru;Solterra AWD;64;179;6.9 sec;160 km/h;320 km;200 Wh/km;480 km/h;â‚¬57', '490;â‚¬56', '395;Â£49', '995;All Wheel Drive;Towbar possible;750;5']
['110;Xpeng;G6 RWD Long Range;87.5;102;6.7 sec;200 km/h;490 km;179 Wh/km;980 km/h;* â‚¬50', '000;* â‚¬50', '000;N/A;Rear Wheel Drive;Towbar possible;;5']
['111;Mini;Cooper SE;49.8;126;6.7 sec;170 km/h;305 km;163 Wh/km;440 km/h;â‚¬36', '900;â‚¬38', '990;Â£34', '500;Front Wheel Drive;;;4']
['112;Hyundai;IONIQ 6 Standard Range 2WD;54;123;8.8 sec;185 km/h;365 km;148 Wh/km;900 km/h;â‚¬43', '900;â‚¬45', '895;N/A;Rear Wheel Drive;Towbar possible;750;5']
['113;Maserati;GranTurismo Folgore;83;480;2.7 sec;325 km/h;420 km;198 Wh/km;920 km/h;â‚¬198', '212;â‚¬199', '250;Â£179', '950;All Wheel Drive;;;4']
['114;Volvo;EX40 Single Motor ER;79;135;7.3 sec;180 km/h;400 km;198 Wh/km;600 km/h;â‚¬55', '490;â‚¬51', '995;Â£47', '705;Rear Wheel Drive;Towbar possible;1500;5']
['115;Toyota;bZ4X AWD;64;181;6.9 sec;160 km/h;315 km;203 Wh/km;470 km/h;â‚¬57', '390;â‚¬52', '995;Â£52', '510;All Wheel Drive;Towbar possible;750;5']
['116;Bmw;iX2 xDrive30;64.7;160;5.6 sec;180 km/h;380 km;170 Wh/km;510 km/h;â‚¬56', '500;â‚¬59', '350;Â£57', '445;All Wheel Drive;Towbar possible;1200;5']
['117;Ford;Explorer Extended Range AWD;79;131;5.3 sec;180 km/h;430 km;184 Wh/km;690 km/h;â‚¬53', '500;â‚¬53', '950;Â£53', '975;All Wheel Drive;Towbar possible;1200;5']
['118;Skoda;Enyaq Coupe 85;77;109;6.7 sec;180 km/h;480 km;160 Wh/km;720 km/h;â‚¬51', '150;â‚¬52', '990;Â£46', '440;Rear Wheel Drive;Towbar possible;1000;5']
['119;Mg;ZS EV Standard Range;49;132;8.6 sec;175 km/h;265 km;185 Wh/km;250 km/h;â‚¬33', '990;â‚¬35', '885;Â£30', '495;Front Wheel Drive;Towbar possible;500;5']
['120;Fisker;Ocean Extreme;106.5;132;3.9 sec;205 km/h;490 km;217 Wh/km;580 km/h;â‚¬63', '590;â‚¬63', '590;Â£57', '900;All Wheel Drive;Towbar possible;1820;5']
['121;Volkswagen;ID.7 Tourer Pro;77;130;6.6 sec;180 km/h;460 km;167 Wh/km;710 km/h;â‚¬54', '795;â‚¬58', '990;* Â£57', '000;Rear Wheel Drive;Towbar possible;1000;5']
['122;Renault;Twingo Electric;21.3;207;12.6 sec;135 km/h;135 km;158 Wh/km;-;â‚¬28', '000;N/A;N/A;Rear Wheel Drive;;;4']
['123;Polestar;4 Long Range Single Motor;94;133;7.4 sec;180 km/h;495 km;190 Wh/km;670 km/h;â‚¬63', '200;â‚¬64', '800;Â£59', '990;Rear Wheel Drive;Towbar possible;1500;5']
['124;Polestar;4 Long Range Dual Motor;94;158;3.8 sec;200 km/h;465 km;202 Wh/km;630 km/h;â‚¬71', '200;â‚¬72', '800;Â£66', '990;All Wheel Drive;Towbar possible;2000;5']
['125;Fisker;Ocean Ultra;106.5;115;4.2 sec;200 km/h;510 km;209 Wh/km;610 km/h;â‚¬58', '900;â‚¬58', '990;Â£50', '900;All Wheel Drive;Towbar possible;1820;5']
['126;Tesla;Model X Plaid;95;271;2.7 sec;262 km/h;455 km;209 Wh/km;630 km/h;â‚¬115', '970;â‚¬115', '993;* Â£120', '000;All Wheel Drive;Towbar possible;2250;7']
['127;Mg;MG4 Electric XPOWER;61.7;137;3.8 sec;200 km/h;320 km;193 Wh/km;560 km/h;â‚¬46', '990;â‚¬42', '285;Â£36', '495;All Wheel Drive;Towbar possible;500;5']
['128;Alfa romeo;Junior Elettrica 54 kWh;50.8;127;9.0 sec;150 km/h;315 km;161 Wh/km;500 km/h;â‚¬39', '500;â‚¬39', '000;* Â£36', '000;Front Wheel Drive;;;5']
['129;Opel;Mokka-e 50 kWh;46.3;154;9.2 sec;150 km/h;260 km;178 Wh/km;420 km/h;â‚¬40', '650;â‚¬36', '999;Â£36', '610;Front Wheel Drive;;;5']

In [57]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', sep=";")

# Access data in the DataFrame using column names or indexing
print(df['model'])
print(df.iloc[0])  # Access first row

<>:4: SyntaxWarning: invalid escape sequence '\T'
<>:4: SyntaxWarning: invalid escape sequence '\T'
C:\Users\FILIPUS FERRY\AppData\Local\Temp\ipykernel_13884\769218957.py:4: SyntaxWarning: invalid escape sequence '\T'
  df = pd.read_csv('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', sep=";")

0                             Model 3
1                             Model Y
2       Model Y Long Range Dual Motor
3       Model 3 Long Range Dual Motor
4              Model Y Long Range RWD
                    ...
348          eVito Tourer Long 60 kWh
349    eVito Tourer Extra-Long 60 kWh
350                        Torres EVX
351                          Aceman E
352                         Aceman SE
Name: model, Length: 353, dtype: object
Row_ID                                                1
title                                             Tesla
model                                           Model 3
battery                                            57.5
price-range                                         104
0 - 100                                         6.1 sec
Top Speed                                      201 km/h
Range*                                           415 km
Efficiency*                                   139 Wh/km
Fastcharge*                                    690 km/h
Germany_price_before_incentives                 €41,970
Netherlands_price_before_incentives             €41,990
UK_price_after_incentives                       £39,990
Drive_Configuration                    Rear Wheel Drive
Tow_Hitch                               Towbar possible
Towing_capacity_in_kg                            1000.0
Number_of_seats                                       5
Name: 0, dtype: object

In [26]:
import csv
file = open("D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv")
csvreader = csv.reader(file)
header = next(csvreader)
print(header)
rows = []
for row in csvreader:
    rows.append(row)
print(rows)
file.close()

<>:2: SyntaxWarning: invalid escape sequence '\T'
<>:2: SyntaxWarning: invalid escape sequence '\T'
C:\Users\FILIPUS FERRY\AppData\Local\Temp\ipykernel_13884\1600083854.py:2: SyntaxWarning: invalid escape sequence '\T'
  file = open("D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv")

['Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats']

In [27]:
import csv
rows = []
with open("D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv", 'r') as file:
    csvreader = csv.reader(file)
    header = next(csvreader)
    for row in csvreader:
        rows.append(row)
print(header)
print(rows)

['Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats']

<>:3: SyntaxWarning: invalid escape sequence '\T'
<>:3: SyntaxWarning: invalid escape sequence '\T'
C:\Users\FILIPUS FERRY\AppData\Local\Temp\ipykernel_13884\464682214.py:3: SyntaxWarning: invalid escape sequence '\T'
  with open("D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv", 'r') as file:

In [28]:
with open('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv') as file:
    content = file.readlines()
header = content[:1]
rows = content[1:]
print(header)
print(rows)

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\FILIPUS FERRY\AppData\Local\Temp\ipykernel_13884\4098013371.py:1: SyntaxWarning: invalid escape sequence '\T'
  with open('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv') as file:

['Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats\n']

In [44]:
import pandas as pd

In [53]:
data= pd.read_csv("D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv",sep=";")
data

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\FILIPUS FERRY\AppData\Local\Temp\ipykernel_13884\896024244.py:1: SyntaxWarning: invalid escape sequence '\T'
  data= pd.read_csv("D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv",sep=";")

,Row_ID,title,model,battery,price-range,0 - 100,Top Speed,Range*,Efficiency*,Fastcharge*,Germany_price_before_incentives,Netherlands_price_before_incentives,UK_price_after_incentives,Drive_Configuration,Tow_Hitch,Towing_capacity_in_kg,Number_of_seats
0,1,Tesla,Model 3,57.5,104,6.1 sec,201 km/h,415 km,139 Wh/km,690 km/h,"€41,970","€41,990","£39,990",Rear Wheel Drive,Towbar possible,1000.0,5
1,2,Tesla,Model Y,57.5,137,6.9 sec,217 km/h,350 km,164 Wh/km,580 km/h,"€45,970","€45,990","£44,990",Rear Wheel Drive,Towbar possible,1600.0,5
2,3,Tesla,Model Y Long Range Dual Motor,75.0,130,5.0 sec,217 km/h,435 km,172 Wh/km,670 km/h,"€55,970","€52,990","£52,990",All Wheel Drive,Towbar possible,1600.0,5
3,4,Tesla,Model 3 Long Range Dual Motor,75.0,106,4.4 sec,201 km/h,500 km,150 Wh/km,770 km/h,"€50,970","€49,990","£49,990",All Wheel Drive,Towbar possible,1000.0,5
4,5,Tesla,Model Y Long Range RWD,75.0,109,5.9 sec,217 km/h,460 km,163 Wh/km,710 km/h,"€49,970","€49,990",NaN,Rear Wheel Drive,Towbar possible,1600.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,349,Mercedes-benz,eVito Tourer Long 60 kWh,60.0,311,12.0 sec,160 km/h,220 km,273 Wh/km,210 km/h,"€68,398",NaN,NaN,Front Wheel Drive,NaN,NaN,8
349,350,Mercedes-benz,eVito Tourer Extra-Long 60 kWh,60.0,322,12.0 sec,160 km/h,215 km,279 Wh/km,200 km/h,"€69,309",NaN,NaN,Front Wheel Drive,NaN,NaN,8
350,351,Kgm,Torres EVX,72.0,130,8.1 sec,175 km/h,350 km,206 Wh/km,390 km/h,"€43,990","€41,250","£44,495",Front Wheel Drive,Towbar possible,1500.0,5
351,352,Mini,Aceman E,38.5,163,7.9 sec,160 km/h,230 km,167 Wh/km,370 km/h,"* €37,000","€38,990","£31,800",Front Wheel Drive,NaN,NaN,5
352,353,Mini,Aceman SE,49.8,137,7.1 sec,170 km/h,300 km,166 Wh/km,430 km/h,"* €40,000","* €42,000","* £36,000",Front Wheel Drive,NaN,NaN,5

In [54]:
data.columns

Index(['Row_ID', 'title', 'model', 'battery', 'price-range', '0 - 100',
       'Top Speed', 'Range*', 'Efficiency*', 'Fastcharge*',
       'Germany_price_before_incentives',
       'Netherlands_price_before_incentives', 'UK_price_after_incentives',
       'Drive_Configuration', 'Tow_Hitch', 'Towing_capacity_in_kg',
       'Number_of_seats'],
      dtype='object')

In [56]:
data.model

0                             Model 3
1                             Model Y
2       Model Y Long Range Dual Motor
3       Model 3 Long Range Dual Motor
4              Model Y Long Range RWD
                    ...
348          eVito Tourer Long 60 kWh
349    eVito Tourer Extra-Long 60 kWh
350                        Torres EVX
351                          Aceman E
352                         Aceman SE
Name: model, Length: 353, dtype: object

In [34]:
import csv

with open('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
       print(row)
       header = ['Name', 'M1 Score', 'M2 Score']
data = [['Alex', 62, 80], ['Brad', 45, 56], ['Joey', 85, 98]]

<>:3: SyntaxWarning: invalid escape sequence '\T'
<>:3: SyntaxWarning: invalid escape sequence '\T'
C:\Users\FILIPUS FERRY\AppData\Local\Temp\ipykernel_13884\993275822.py:3: SyntaxWarning: invalid escape sequence '\T'
  with open('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', 'r') as csvfile:

{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '1;Tesla;Model 3;57.5;104;6.1 sec;201 km/h;415 km;139 Wh/km;690 km/h;â‚¬41', None: ['970;â‚¬41', '990;Â£39', '990;Rear Wheel Drive;Towbar possible;1000;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '2;Tesla;Model Y;57.5;137;6.9 sec;217 km/h;350 km;164 Wh/km;580 km/h;â‚¬45', None: ['970;â‚¬45', '990;Â£44', '990;Rear Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '3;Tesla;Model Y Long Range Dual Motor;75;130;5.0 sec;217 km/h;435 km;172 Wh/km;670 km/h;â‚¬55', None: ['970;â‚¬52', '990;Â£52', '990;All Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '4;Tesla;Model 3 Long Range Dual Motor;75;106;4.4 sec;201 km/h;500 km;150 Wh/km;770 km/h;â‚¬50', None: ['970;â‚¬49', '990;Â£49', '990;All Wheel Drive;Towbar possible;1000;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '5;Tesla;Model Y Long Range RWD;75;109;5.9 sec;217 km/h;460 km;163 Wh/km;710 km/h;â‚¬49', None: ['970;â‚¬49', '990;N/A;Rear Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '6;Byd;ATTO 3;60.5;121;7.3 sec;160 km/h;330 km;183 Wh/km;370 km/h;â‚¬37', None: ['990;â‚¬38', '990;Â£37', '195;Front Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '7;Mg;MG4 Electric 64 kWh;61.7;102;7.9 sec;160 km/h;360 km;171 Wh/km;630 km/h;â‚¬39', None: ['990;â‚¬35', '785;Â£29', '495;Rear Wheel Drive;Towbar possible;500;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '8;Byd;SEAL 82.5 kWh AWD Excellence;82.5;107;3.8 sec;180 km/h;490 km;168 Wh/km;540 km/h;â‚¬50', None: ['990;â‚¬50', '990;Â£48', '695;All Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '9;Tesla;Model Y Performance;75;152;3.8 sec;250 km/h;415 km;181 Wh/km;640 km/h;â‚¬60', None: ['790;â‚¬58', '990;Â£59', '990;All Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '10;Bmw;i4 eDrive40;80.7;122;5.7 sec;190 km/h;515 km;157 Wh/km;800 km/h;â‚¬59', None: ['200;â‚¬62', '992;Â£57', '890;Rear Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '11;Citroen;e-C3;44;90;11.0 sec;135 km/h;265 km;166 Wh/km;340 km/h;â‚¬23', None: ['300;â‚¬24', '290;* Â£21', '000;Front Wheel Drive;Towbar possible;550;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '12;Bmw;iX xDrive40;71;225;6.1 sec;200 km/h;360 km;197 Wh/km;480 km/h;â‚¬77', None: ['300;â‚¬84', '998;Â£69', '905;All Wheel Drive;Towbar possible;2500;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '13;Volkswagen;ID.4 Pro;77;114;6.7 sec;180 km/h;435 km;177 Wh/km;650 km/h;â‚¬46', None: ['335;â‚¬49', '990;Â£46', '035;Rear Wheel Drive;Towbar possible;1000;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '14;Byd;DOLPHIN 60.4 kWh;60.5;101;7.0 sec;160 km/h;340 km;178 Wh/km;340 km/h;â‚¬32', None: ['990;â‚¬35', '490;Â£30', '195;Front Wheel Drive;Towbar possible;0;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '15;Volvo;EX30 Single Motor ER;64;118;5.3 sec;180 km/h;360 km;178 Wh/km;600 km/h;â‚¬41', None: ['790;â‚¬41', '495;Â£38', '545;Rear Wheel Drive;Towbar possible;1400;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '16;Tesla;Model S Plaid;95;199;2.3 sec;282 km/h;560 km;170 Wh/km;780 km/h;â‚¬110', None: ['970;â‚¬108', '990;* Â£100', '000;All Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '17;Tesla;Model S Dual Motor;95;167;3.2 sec;250 km/h;575 km;165 Wh/km;800 km/h;â‚¬95', None: ['970;â‚¬93', '990;* Â£85', '000;All Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '18;Kia;Niro EV;64.8;111;7.8 sec;167 km/h;385 km;168 Wh/km;390 km/h;â‚¬45', None: ['690;â‚¬39', '995;Â£37', '295;Front Wheel Drive;Towbar possible;750;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '19;Hyundai;Kona Electric 65 kWh;65.4;116;7.8 sec;170 km/h;390 km;168 Wh/km;400 km/h;â‚¬47', None: ['190;â‚¬43', '995;Â£38', '595;Front Wheel Drive;Towbar possible;750;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '20;Tesla;Model 3 Performance;75;135;3.2 sec;262 km/h;455 km;165 Wh/km;700 km/h;â‚¬57', None: ['970;â‚¬56', '990;Â£59', '990;All Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '21;Byd;HAN;85.4;146;3.9 sec;180 km/h;475 km;180 Wh/km;450 km/h;â‚¬69', None: ['020;â‚¬69', '990;N/A;All Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '22;Cupra;Born 150 kW - 58 kWh;58;113;7.3 sec;160 km/h;350 km;166 Wh/km;470 km/h;â‚¬39', None: ['370;â‚¬36', '939;Â£36', '475;Rear Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '23;Fiat;500e Hatchback 42 kWh;37.3;149;9.0 sec;150 km/h;235 km;159 Wh/km;390 km/h;â‚¬34', None: ['990;â‚¬34', '490;Â£31', '195;Front Wheel Drive;;;4']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '24;Byd;SEAL 82.5 kWh RWD Design;82.5;96;5.9 sec;180 km/h;500 km;165 Wh/km;550 km/h;â‚¬44', None: ['990;â‚¬45', '990;Â£45', '695;Rear Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '25;Byd;TANG;86.4;199;4.6 sec;180 km/h;355 km;243 Wh/km;420 km/h;â‚¬71', None: ['400;â‚¬69', '990;N/A;All Wheel Drive;Towbar possible;1500;7']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '26;Dacia;Spring Electric 45;25;137;19.1 sec;125 km/h;165 km;152 Wh/km;180 km/h;â‚¬22', None: ['550;N/A;N/A;Front Wheel Drive;;;4']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '27;Renault;Scenic E-Tech EV87 220hp;87;98;7.9 sec;170 km/h;490 km;178 Wh/km;510 km/h;â‚¬48', None: ['900;â‚¬47', '970;Â£40', '995;Front Wheel Drive;Towbar possible;1100;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '28;Bmw;iX3;74;184;6.8 sec;180 km/h;385 km;192 Wh/km;520 km/h;â‚¬67', None: ['300;â‚¬71', '462;Â£64', '165;Rear Wheel Drive;Towbar possible;750;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '29;Bmw;iX1 xDrive30;64.7;147;5.6 sec;180 km/h;380 km;170 Wh/km;510 km/h;â‚¬55', None: ['000;â‚¬57', '850;Â£47', '465;All Wheel Drive;Towbar possible;1200;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '30;Tesla;Model Y;57.5;137;6.9 sec;217 km/h;350 km;164 Wh/km;810 km/h;â‚¬45', None: ['970;â‚¬45', '990;Â£44', '990;Rear Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '31;Skoda;Enyaq 85;77;111;6.7 sec;180 km/h;450 km;171 Wh/km;670 km/h;â‚¬48', None: ['900;â‚¬49', '990;Â£44', '540;Rear Wheel Drive;Towbar possible;1000;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '32;Nio;ET7 75 kWh;70.5;208;3.8 sec;200 km/h;400 km;176 Wh/km;600 km/h;â‚¬81', None: ['900;â‚¬84', '900;N/A;All Wheel Drive;Towbar possible;2000;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '33;Audi;Q6 e-tron quattro;94.9;170;5.9 sec;210 km/h;460 km;206 Wh/km;920 km/h;â‚¬74', None: ['700;* â‚¬80', '000;Â£68', '975;All Wheel Drive;Towbar possible;2400;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '34;Byd;SEAL U 71.8 kWh Comfort;71.8;126;9.3 sec;175 km/h;340 km;211 Wh/km;320 km/h;N/A;â‚¬42', None: ['990;N/A;Front Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '35;Mg;ZS EV Long Range;68.3;105;8.4 sec;175 km/h;370 km;185 Wh/km;420 km/h;â‚¬37', None: ['990;â‚¬40', '185;Â£32', '995;Front Wheel Drive;Towbar possible;500;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '36;Toyota;bZ4X FWD;64;144;7.5 sec;160 km/h;340 km;188 Wh/km;510 km/h;â‚¬47', None: ['490;â‚¬45', '995;Â£46', '110;Front Wheel Drive;Towbar possible;750;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '37;Renault;5 E-Tech 52kWh 150hp;52;97;7.5 sec;150 km/h;330 km;158 Wh/km;420 km/h;* â‚¬32', None: ['000;* â‚¬32', '000;* Â£28', '000;Front Wheel Drive;Towbar possible;500;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '38;Bmw;i4 M50;80.7;170;3.9 sec;225 km/h;450 km;179 Wh/km;700 km/h;â‚¬70', None: ['800;â‚¬76', '786;Â£71', '085;All Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '39;Renault;Megane E-Tech EV60 220hp;60;113;7.4 sec;160 km/h;380 km;158 Wh/km;530 km/h;â‚¬46', None: ['600;â‚¬39', '370;Â£36', '995;Front Wheel Drive;Towbar possible;900;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '40;Rolls-royce;Spectre;102;828;4.5 sec;250 km/h;465 km;219 Wh/km;540 km/h;â‚¬379', None: ['015;â‚¬396', '275;Â£330', '000;All Wheel Drive;;;4']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '41;Kia;EV6 Long Range 2WD;74;126;7.3 sec;185 km/h;410 km;180 Wh/km;1070 km/h;â‚¬51', None: ['990;â‚¬50', '995;Â£45', '245;Rear Wheel Drive;Towbar possible;1600;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '42;Honda;e:Ny1;61.9;147;7.6 sec;160 km/h;335 km;185 Wh/km;300 km/h;â‚¬47', None: ['590;â‚¬48', '750;Â£44', '995;Front Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '43;Volkswagen;ID.3 Pro;58;122;7.3 sec;160 km/h;350 km;166 Wh/km;450 km/h;â‚¬39', None: ['995;â‚¬44', '990;Â£37', '115;Rear Wheel Drive;Towbar possible;0;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '44;Renault;Zoe ZE50 R110;52;114;11.4 sec;135 km/h;315 km;165 Wh/km;230 km/h;â‚¬36', None: ['840;â‚¬34', '895;N/A;Front Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '45;Nissan;Leaf;39;144;7.9 sec;144 km/h;235 km;166 Wh/km;230 km/h;â‚¬33', None: ['400;â‚¬35', '090;Â£28', '995;Front Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '46;Lucid;Air Grand Touring;112;196;3.0 sec;270 km/h;665 km;168 Wh/km;840 km/h;â‚¬129', None: ['000;â‚¬132', '000;N/A;All Wheel Drive;;;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '47;Hongqi;E-HS9 99 kWh;90;216;4.9 sec;200 km/h;370 km;243 Wh/km;430 km/h;N/A;â‚¬79', None: ['995;N/A;All Wheel Drive;Towbar possible;1500;5']}
{'Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats': '48;Cupra;Born 170 kW - 77 kWh;77;105;7.0 sec;160 km/h;450 km;171 Wh/km;630 km/h;â‚¬46', None: ['450;â‚¬46', '989;Â£41', '975;Rear Wheel Drive;;;4']}

In [35]:
header = ['Name', 'M1 Score', 'M2 Score']
data = [['Alex', 62, 80], ['Brad', 45, 56], ['Joey', 85, 98]]

In [37]:
import csv

filename = 'Students_Data.csv'
with open(filename, 'w', newline="") as file:
    csvwriter = csv.writer(file) # 2. create a csvwriter object
    csvwriter.writerow(header) # 4. write the header
    csvwriter.writerows(data) # 5. write the rest of the data
header = ['Name', 'M1 Score', 'M2 Score']
data = [['Alex', 62, 80], ['Brad', 45, 56], ['Joey', 85, 98]]
filename = 'Student_scores.csv'
with open(filename, 'w') as file:
    for header in header:
        file.write(str(header)+', ')
    file.write('n')
    for row in data:
        for x in row:
            file.write(str(x)+', ')
        file.write('n')

In [38]:
import pandas as pd

header = ['Name', 'M1 Score', 'M2 Score']
data = [['Alex', 62, 80], ['Brad', 45, 56], ['Joey', 85, 98]]
data = pd.DataFrame(data, columns=header)
data.to_csv('Stu_data.csv', index=False)

In [40]:
import csv

data = [{'Name': 'Alex', 'M1 Score': 62, 'M2 Score': 80},
        {'Name': 'Brad', 'M1 Score': 45, 'M2 Score': 56},
        {'Name': 'Joey', 'M1 Score': 85, 'M2 Score': 98}]

fieldnames = ['Name', 'M1 Score', 'M2 Score']

with open('Students_Data.csv', 'w', newline='') as csvfile: 
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data)

WEB_2 : 3.1. Statistics in Python

https://scipy-lectures.org/packages/statistics/index.html

In [58]:
import pandas
data = pandas.read_csv('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', sep=';', na_values=".")
data

<>:2: SyntaxWarning: invalid escape sequence '\T'
<>:2: SyntaxWarning: invalid escape sequence '\T'
C:\Users\FILIPUS FERRY\AppData\Local\Temp\ipykernel_13884\1109024021.py:2: SyntaxWarning: invalid escape sequence '\T'
  data = pandas.read_csv('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', sep=';', na_values=".")

,Row_ID,title,model,battery,price-range,0 - 100,Top Speed,Range*,Efficiency*,Fastcharge*,Germany_price_before_incentives,Netherlands_price_before_incentives,UK_price_after_incentives,Drive_Configuration,Tow_Hitch,Towing_capacity_in_kg,Number_of_seats
0,1,Tesla,Model 3,57.5,104,6.1 sec,201 km/h,415 km,139 Wh/km,690 km/h,"€41,970","€41,990","£39,990",Rear Wheel Drive,Towbar possible,1000.0,5
1,2,Tesla,Model Y,57.5,137,6.9 sec,217 km/h,350 km,164 Wh/km,580 km/h,"€45,970","€45,990","£44,990",Rear Wheel Drive,Towbar possible,1600.0,5
2,3,Tesla,Model Y Long Range Dual Motor,75.0,130,5.0 sec,217 km/h,435 km,172 Wh/km,670 km/h,"€55,970","€52,990","£52,990",All Wheel Drive,Towbar possible,1600.0,5
3,4,Tesla,Model 3 Long Range Dual Motor,75.0,106,4.4 sec,201 km/h,500 km,150 Wh/km,770 km/h,"€50,970","€49,990","£49,990",All Wheel Drive,Towbar possible,1000.0,5
4,5,Tesla,Model Y Long Range RWD,75.0,109,5.9 sec,217 km/h,460 km,163 Wh/km,710 km/h,"€49,970","€49,990",NaN,Rear Wheel Drive,Towbar possible,1600.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,349,Mercedes-benz,eVito Tourer Long 60 kWh,60.0,311,12.0 sec,160 km/h,220 km,273 Wh/km,210 km/h,"€68,398",NaN,NaN,Front Wheel Drive,NaN,NaN,8
349,350,Mercedes-benz,eVito Tourer Extra-Long 60 kWh,60.0,322,12.0 sec,160 km/h,215 km,279 Wh/km,200 km/h,"€69,309",NaN,NaN,Front Wheel Drive,NaN,NaN,8
350,351,Kgm,Torres EVX,72.0,130,8.1 sec,175 km/h,350 km,206 Wh/km,390 km/h,"€43,990","€41,250","£44,495",Front Wheel Drive,Towbar possible,1500.0,5
351,352,Mini,Aceman E,38.5,163,7.9 sec,160 km/h,230 km,167 Wh/km,370 km/h,"* €37,000","€38,990","£31,800",Front Wheel Drive,NaN,NaN,5
352,353,Mini,Aceman SE,49.8,137,7.1 sec,170 km/h,300 km,166 Wh/km,430 km/h,"* €40,000","* €42,000","* £36,000",Front Wheel Drive,NaN,NaN,5

In [59]:
import numpy as np
t = np.linspace(-6, 6, 20)
sin_t = np.sin(t)
cos_t = np.cos(t)
pandas.DataFrame({'t': t, 'sin': sin_t, 'cos': cos_t})

           t       sin       cos
0  -6.000000  0.279415  0.960170
1  -5.368421  0.792419  0.609977
2  -4.736842  0.999701  0.024451
3  -4.105263  0.821291 -0.570509
4  -3.473684  0.326021 -0.945363
5  -2.842105 -0.295030 -0.955488
6  -2.210526 -0.802257 -0.596979
7  -1.578947 -0.999967 -0.008151
8  -0.947368 -0.811882  0.583822
9  -0.315789 -0.310567  0.950551
10  0.315789  0.310567  0.950551
11  0.947368  0.811882  0.583822
12  1.578947  0.999967 -0.008151
13  2.210526  0.802257 -0.596979
14  2.842105  0.295030 -0.955488
15  3.473684 -0.326021 -0.945363
16  4.105263 -0.821291 -0.570509
17  4.736842 -0.999701  0.024451
18  5.368421 -0.792419  0.609977
19  6.000000 -0.279415  0.960170

In [60]:
data.shape    # 40 rows and 8 columns

(353, 17)

In [61]:
data.columns  # It has columns

Index(['Row_ID', 'title', 'model', 'battery', 'price-range', '0 - 100',
       'Top Speed', 'Range*', 'Efficiency*', 'Fastcharge*',
       'Germany_price_before_incentives',
       'Netherlands_price_before_incentives', 'UK_price_after_incentives',
       'Drive_Configuration', 'Tow_Hitch', 'Towing_capacity_in_kg',
       'Number_of_seats'],
      dtype='object')

In [62]:
print(data['title'])  # Columns can be addressed by name

0              Tesla
1              Tesla
2              Tesla
3              Tesla
4              Tesla
           ...
348    Mercedes-benz
349    Mercedes-benz
350              Kgm
351             Mini
352             Mini
Name: title, Length: 353, dtype: object

In [ ]:
# Simpler selector
data[data['title'] == 'Tesla']['battery'].mean()

np.float64(77.29166666666667)

In [ ]:
groupby_title = data.groupby('title')
for title, value in groupby_title['batery']:
    print((title, value.mean()))

('Abarth', np.float64(37.8))
('Aiways', np.float64(60.0))
('Alfa romeo', np.float64(50.8))
('Audi', np.float64(89.55714285714285))
('Bmw', np.float64(81.77368421052633))
('Byd', np.float64(70.64))
('Citroen', np.float64(48.31428571428571))
('Cupra', np.float64(71.0))
('Dacia', np.float64(25.0))
('Ds', np.float64(50.8))
('E.go', np.float64(27.0))
('Elaris', np.float64(81.0))
('Fiat', np.float64(32.371428571428574))
('Fisker', np.float64(94.66666666666667))
('Ford', np.float64(78.275))
('Genesis', np.float64(75.7))
('Gwm', np.float64(54.666666666666664))
('Honda', np.float64(61.9))
('Hongqi', np.float64(92.83333333333333))
('Hyundai', np.float64(66.42222222222222))
('Jaguar', np.float64(84.7))
('Jeep', np.float64(50.8))
('Kgm', np.float64(72.0))
('Kia', np.float64(73.2))
('Lancia', np.float64(48.1))
('Lexus', np.float64(64.0))
('Lotus', np.float64(104.5))
('Lucid', np.float64(98.66666666666667))
('Maserati', np.float64(87.0))
('Maxus', np.float64(84.0))
('Mazda', np.float64(30.0))
('Mercedes-benz', np.float64(87.95405405405404))
('Mg', np.float64(60.92999999999999))
('Mini', np.float64(50.71666666666667))
('Nio', np.float64(80.25))
('Nissan', np.float64(66.71428571428571))
('Opel', np.float64(48.849999999999994))
('Peugeot', np.float64(65.09166666666665))
('Polestar', np.float64(88.25))
('Porsche', np.float64(93.86))
('Renault', np.float64(50.775))
('Rolls-royce', np.float64(102.0))
('Seres', np.float64(51.0))
('Skoda', np.float64(72.25))
('Smart', np.float64(58.666666666666664))
('Ssangyong', np.float64(56.0))
('Subaru', np.float64(64.0))
('Tesla', np.float64(77.29166666666667))
('Toyota', np.float64(64.0))
('Vinfast', np.float64(99.46666666666665))
('Volkswagen', np.float64(77.35))
('Volvo', np.float64(78.57142857142857))
('Voyah', np.float64(100.0))
('Xpeng', np.float64(83.45555555555556))
('Zeekr', np.float64(82.0))

In [72]:
print(data.dtypes)
data['battery'] = pd.to_numeric(data['battery'], errors='coerce')
groupby_title = data.groupby('title').mean(numeric_only=True)
print(groupby_title)

Row_ID                                   int64
title                                   object
model                                   object
battery                                float64
price-range                              int64
0 - 100                                 object
Top Speed                               object
Range*                                  object
Efficiency*                             object
Fastcharge*                             object
Germany_price_before_incentives         object
Netherlands_price_before_incentives     object
UK_price_after_incentives               object
Drive_Configuration                     object
Tow_Hitch                               object
Towing_capacity_in_kg                  float64
Number_of_seats                          int64
dtype: object
                   Row_ID     battery  price-range  Towing_capacity_in_kg  \
title
Abarth         302.000000   37.800000   179.000000                    NaN
Aiways         291.500000   60.000000   134.500000                    NaN
Alfa romeo     107.000000   50.800000   139.500000                    NaN
Audi           192.714286   89.557143   170.928571            1600.000000
Bmw            115.000000   81.773684   200.263158            1644.117647
Byd             64.500000   70.640000   125.000000             750.000000
Citroen        200.142857   48.314286   132.857143             683.333333
Cupra          147.000000   71.000000   119.000000                    NaN
Dacia          115.750000   25.000000   130.750000                    NaN
Ds             246.000000   50.800000   137.000000                    NaN
E.go           295.000000   27.000000   167.000000                    NaN
Elaris         327.000000   81.000000   136.000000                    NaN
Fiat           232.714286   32.371429   185.428571                    NaN
Fisker         169.666667   94.666667   123.666667            1576.666667
Ford           170.000000   78.275000   147.625000            1056.250000
Genesis        287.800000   75.700000   181.800000            1650.000000
Gwm            236.000000   54.666667   141.000000                    NaN
Honda           42.000000   61.900000   147.000000                    NaN
Hongqi         180.333333   92.833333   219.666667            1500.000000
Hyundai         72.000000   66.422222   140.111111            1093.750000
Jaguar         176.000000   84.700000   235.000000             750.000000
Jeep            78.000000   50.800000   127.000000                    NaN
Kgm            351.000000   72.000000   130.000000            1500.000000
Kia            116.900000   73.200000   154.000000            1377.777778
Lancia         141.000000   48.100000   131.000000                    NaN
Lexus          176.000000   64.000000   189.500000             750.000000
Lotus          231.833333  104.500000   259.000000            2250.000000
Lucid          150.666667   98.666667   174.000000                    NaN
Maserati       147.000000   87.000000   441.000000            1800.000000
Maxus          103.000000   84.000000   197.000000            1000.000000
Mazda           85.000000   30.000000   212.000000                    NaN
Mercedes-benz  241.891892   87.954054   232.594595            1243.548387
Mg             116.200000   60.930000   120.600000             550.000000
Mini           226.333333   50.716667   138.500000             975.000000
Nio            215.200000   80.250000   183.800000            1600.000000
Nissan         170.000000   66.714286   144.142857            1200.000000
Opel           177.666667   48.850000   135.833333               0.000000
Peugeot        181.833333   65.091667   135.750000            1200.000000
Polestar       166.125000   88.250000   145.000000            1737.500000
Porsche        270.150000   93.860000   303.550000            2000.000000
Renault        132.833333   50.775000   126.416667             788.888889
Rolls-royce     40.000000  102.000000   828.000000                    NaN
Seres          206.000000   51.000000   146.000000                    NaN
Skoda          196.750000   72.250000   125.750000            1075.000000
Smart          211.000000   58.666667   139.333333            1600.000000
Ssangyong      203.000000   56.000000   139.000000            1500.000000
Subaru         109.000000   64.000000   179.000000             750.000000
Tesla           27.000000   77.291667   156.083333            1609.090909
Toyota          75.500000   64.000000   162.500000             750.000000
Vinfast        279.666667   99.466667   146.666667                    NaN
Volkswagen     154.350000   77.350000   147.000000            1000.000000
Volvo          196.357143   78.571429   159.285714            1628.571429
Voyah          162.000000  100.000000   154.000000            2000.000000
Xpeng          196.111111   83.455556   129.555556            1500.000000
Zeekr          165.800000   82.000000   130.200000            1740.000000

               Number_of_seats
title
Abarth                4.000000
Aiways                5.000000
Alfa romeo            5.000000
Audi                  5.000000
Bmw                   5.000000
Byd                   5.200000
Citroen               5.285714
Cupra                 4.666667
Dacia                 4.000000
Ds                    5.000000
E.go                  4.000000
Elaris                5.000000
Fiat                  4.142857
Fisker                5.000000
Ford                  5.000000
Genesis               5.000000
Gwm                   5.000000
Honda                 5.000000
Hongqi                5.000000
Hyundai               5.000000
Jaguar                5.000000
Jeep                  5.000000
Kgm                   5.000000
Kia                   5.600000
Lancia                5.000000
Lexus                 5.000000
Lotus                 5.000000
Lucid                 5.000000
Maserati              4.333333
Maxus                 7.000000
Mazda                 5.000000
Mercedes-benz         5.756757
Mg                    5.000000
Mini                  4.666667
Nio                   5.000000
Nissan                5.000000
Opel                  5.000000
Peugeot               5.500000
Polestar              5.000000
Porsche               4.850000
Renault               4.916667
Rolls-royce           4.000000
Seres                 5.000000
Skoda                 5.000000
Smart                 5.000000
Ssangyong             5.000000
Subaru                5.000000
Tesla                 5.333333
Toyota                5.000000
Vinfast               5.666667
Volkswagen            5.150000
Volvo                 5.428571
Voyah                 5.000000
Xpeng                 5.000000
Zeekr                 5.000000

In [7]:
import pandas as pd
from pandas.plotting import scatter_matrix

# Contoh: Membaca dataset dari file CSV
data = pd.read_csv("cars_data_RAW.csv")  # Ganti dengan path file yang benar

# Cek apakah data sudah terbaca
print(data.head())

# Visualisasi scatter matrix
scatter_matrix(data[['Range*', 'Efficiency*', 'Fastcharge*']])

                                                                                                           Row_ID;title;model;battery;price-range;0 - 100;Top Speed;Range*;Efficiency*;Fastcharge*;Germany_price_before_incentives;Netherlands_price_before_incentives;UK_price_after_incentives;Drive_Configuration;Tow_Hitch;Towing_capacity_in_kg;Number_of_seats
1;Tesla;Model 3;57.5;104;6.1 sec;201 km/h;415 k... 970;€41 990;£39                                                990;Rear Wheel Drive;Towbar possible;1000;5
2;Tesla;Model Y;57.5;137;6.9 sec;217 km/h;350 k... 970;€45 990;£44                                                990;Rear Wheel Drive;Towbar possible;1600;5
3;Tesla;Model Y Long Range Dual Motor;75;130;5.... 970;€52 990;£52                                                 990;All Wheel Drive;Towbar possible;1600;5
4;Tesla;Model 3 Long Range Dual Motor;75;106;4.... 970;€49 990;£49                                                 990;All Wheel Drive;Towbar possible;1000;5
5;Tesla;Model Y Long Range RWD;75;109;5.9 sec;2... 970;€49 990;N/A;Rear Wheel Drive;Towbar possible;1600;5                                                NaN

KeyError: "None of [Index(['Range*', 'Efficiency*', 'Fastcharge*'], dtype='object')] are in the [columns]"

In [11]:
scatter_matrix(data[['range', 'efficiency', 'fastcharge']])  # Sesuaikan dengan yang benar

KeyError: "None of [Index(['range', 'efficiency', 'fastcharge'], dtype='object')] are in the [columns]"

In [3]:
from pandas.tools import plotting
plotting.scatter_matrix(data[['Range', 'Efficiency', 'Fastcharge']])

ModuleNotFoundError: No module named 'pandas.tools'

In [ ]:
plotting.scatter_matrix(data[['Price-range', '0-100', 'Top Speed']])

In [ ]:
from scipy import stats

In [ ]:
stats.ttest_1samp(data['Price-range'], 0)

In [ ]:
tesla_viq = data[data['title'] == 'Tesla']['Price-range']
bmw_viq = data[data['title'] == 'BMW']['Price-range']
stats.ttest_ind(tesla_viq, bmw_viq)

In [ ]:
stats.ttest_ind(data['0-100'], data['Top Speed'])

In [ ]:
stats.ttest_rel(data['0-100'], data['Top Speed'])

In [ ]:
stats.ttest_1samp(data['0-100'] - data['Top Speed'], 0)

In [ ]:
stats.wilcoxon(data['0-100'], data['Top Speed'])

In [ ]:
import numpy as np
x = np.linspace(-5, 5, 20)
np.random.seed(1)
# normal distributed noise
y = -5 + 3*x + 4 * np.random.normal(size=x.shape)
# Create a data frame containing all the relevant variables
data = pandas.DataFrame({'x': x, 'y': y})

In [ ]:
from statsmodels.formula.api import ols
model = ols("y ~ x", data).fit()

In [ ]:
print(model.summary())

In [ ]:
data = pandas.read_csv('D:\TUGAS KULIAH\SEMESTER 4\Machine Learning\Praktikum\Prak-1\cars_data_RAW.csv', sep=';', na_values=".")

In [ ]:
model = ols("Price-range ~ title + 1", data).fit()
print(model.summary())

In [ ]:
model = ols('Price-range ~ C(title)', data).fit()

In [ ]:
data_fisq = pandas.DataFrame({'iq': data['FSIQ'], 'type': 'fsiq'})
data_piq = pandas.DataFrame({'iq': data['PIQ'], 'type': 'piq'})
data_long = pandas.concat((data_fisq, data_piq))
print(data_long)  
model = ols("iq ~ type", data_long).fit()
print(model.summary())

In [ ]:
stats.ttest_ind(data['FSIQ'], data['PIQ'])

In [ ]:
data = pandas.read_csv('examples/iris.csv')
model = ols('sepal_width ~ name + petal_length', data).fit()
print(model.summary())

In [ ]:
print(model.f_test([0, 1, -1, 0]))

In [ ]:
print(data)

In [ ]:
import seaborn
seaborn.pairplot(data, vars=['WAGE', 'AGE', 'EDUCATION'],kind='reg')

In [ ]:
seaborn.pairplot(data, vars=['WAGE', 'AGE', 'EDUCATION'],kind='reg', hue='SEX')

In [ ]:
from matplotlib import pyplot as plt
plt.rcdefaults()

In [ ]:
seaborn.lmplot(y='WAGE', x='EDUCATION', data=data)

In [ ]:
result = sm.ols(formula='wage ~ education + gender + education * gender',data=data).fit()    
print(result.summary())

WEB_3 : Pandas DataFrame describe() Method

https://www.geeksforgeeks.org/python-pandas-dataframe-describe-method/

In [1]:
print("Hello World!")

Hello World!